name: Start tests and deploy
on:
  push:
jobs:
  load:
    runs-on: windows-latest
    steps:                
    - name: Checkout       
      uses: actions/checkout@v4.1.6
    - name: Dependencies
      run:  pip install -r ./requirements.txt 